# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_t <- function(t, ns_parmlist) {
    .Call('gfmodel11_f_t', PACKAGE = 'gfmodel11', t, ns_parmlist)
}

f_t_msm <- function(t, ns_parmlist) {
    .Call('gfmodel11_f_t_msm', PACKAGE = 'gfmodel11', t, ns_parmlist)
}

source_size <- function(t, parms) {
    .Call('gfmodel11_source_size', PACKAGE = 'gfmodel11', t, parms)
}

F_from_state <- function(t, y, parms) {
    .Call('gfmodel11_F_from_state', PACKAGE = 'gfmodel11', t, y, parms)
}

G_from_state <- function(t, y, parms) {
    .Call('gfmodel11_G_from_state', PACKAGE = 'gfmodel11', t, y, parms)
}

dydt <- function(t, y, parms) {
    .Call('gfmodel11_dydt', PACKAGE = 'gfmodel11', t, y, parms)
}

rcpp_hello_world <- function() {
    .Call('gfmodel11_rcpp_hello_world', PACKAGE = 'gfmodel11')
}

